source 'https://rubygems.org'
ruby '2.1.2'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'pry'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'sinatra-simple-authentication'
gem 'rack-flash3'